name: CI

on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04

    container:
      image: ortegaguillermo/apache-php:7.2
      options: --cpus 1
      ports:
        - 3364

    steps:
    - uses: actions/checkout@v1

    - name: Install Composer
      run: |
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        cp .env.example .env
        php artisan key:generate;

    - name: Unit Tests
      run: |
        php vendor/bin/phpunit --debug